"""proveedores y reparaciones (bloque de service / RMA).

Cubre los pendientes **19** (bloque de service/RMA) y **18** (que la accion
"Reemplazar equipo" lo contemple) de la pagina del wiki. El 19 estaba frenado
explicitamente por implicar tabla nueva, que es lo que la cadena de Alembic
—traida el 2026-08-03 por la revision anterior— vino a destrabar.

**Dos tablas nuevas y ninguna columna alterada**, asi que esta revision no tiene
nada del filo de la 0002: no hay `ALTER TABLE` crudo, no hay FK agregada sobre
una tabla con datos y no se reconstruye nada. Las FK de `equipos_reparaciones`
viajan dentro del `CREATE TABLE`, que es donde SQLite si las acepta.

**El autogenerate salio usable tal cual**, que era la apuesta al elegir
`include_name` sobre el `target_metadata = None` de Gestiolibra: las dos tablas
entraron solas por estar sus modulos en la lista de `app/schema.py`, y no
propuso dropear ninguna de las 5 tablas de `libraauth`/`libracore` que comparten
el archivo. Lo unico que se edito a mano es este docstring.

**No hay backfill.** Las reparaciones historicas no existen como dato: hasta hoy
un paso por service dejaba una frase en el `motivo` de un movimiento, texto libre
del que no se puede derivar proveedor ni RMA. Mismo criterio que se tomo con el
`equipo_id` de las incidencias migradas (pendiente 21): la historia hacia atras
se deja como esta y el registro empieza de aca en adelante.
"""
from alembic import op
import sqlalchemy as sa

revision = '0003_proveedores_y_reparaciones'
down_revision = '0002_categorias_y_datos_fiscales'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('equipos_reparaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipo_id', sa.Integer(), nullable=False),
    sa.Column('incidencia_id', sa.Integer(), nullable=True),
    sa.Column('proveedor_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.Date(), nullable=False),
    sa.Column('fecha_retorno', sa.Date(), nullable=True),
    sa.Column('remito_salida', sa.String(length=100), nullable=True),
    sa.Column('rma', sa.String(length=100), nullable=True),
    sa.Column('en_garantia', sa.Boolean(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos.id'], ),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equipos_reparaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipos_reparaciones_equipo_id'), ['equipo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_reparaciones_fecha_envio'), ['fecha_envio'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_reparaciones_fecha_retorno'), ['fecha_retorno'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_reparaciones_incidencia_id'), ['incidencia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipos_reparaciones_proveedor_id'), ['proveedor_id'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipos_reparaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipos_reparaciones_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_reparaciones_incidencia_id'))
        batch_op.drop_index(batch_op.f('ix_equipos_reparaciones_fecha_retorno'))
        batch_op.drop_index(batch_op.f('ix_equipos_reparaciones_fecha_envio'))
        batch_op.drop_index(batch_op.f('ix_equipos_reparaciones_equipo_id'))

    op.drop_table('equipos_reparaciones')
    op.drop_table('proveedores')
    # ### end Alembic commands ###
