"""alquileres: activos y contratos de equipos (fase 1).

Primera fase del modulo de alquiler y cesion de equipos, disenado el 2026-08-04
en `wiki/analyses/libradesk-alquiler-de-equipos-diseno.md`. Cubre el contrato,
sus equipos y su historial de precios; las cuotas, las actas y la union con el
service son fases posteriores.

**Cuatro tablas nuevas y ninguna columna alterada**, asi que —igual que la
0003— no tiene nada del filo de la 0002: no hay `ALTER TABLE` crudo, no hay FK
agregada sobre una tabla con datos y no se reconstruye nada. Las FK viajan
dentro del `CREATE TABLE`, que es donde SQLite si las acepta. **Ninguna tabla
existente se toca**: `equipos`, `incidencias` y `clientes` quedan como estaban,
que era la razon de haber elegido `activos` como tabla separada.

**El autogenerate salio usable tal cual** —lo unico editado a mano es este
docstring—, y no propuso dropear ninguna de las 5 tablas de
`libraauth`/`libracore` que comparten el archivo SQLite: es el `include_name`
de `app/schema.py` haciendo su trabajo.

**No hay backfill.** Los alquileres que hoy existan viven fuera del sistema (en
papel o en una planilla) y no hay dato del que derivarlos: ni el activo, ni la
fecha de instalacion, ni la serie de precios. Mismo criterio que tomo la 0003
con las reparaciones historicas — la historia hacia atras se deja como esta y el
registro empieza de aca en adelante.

> Si al mergear esta rama ya existe otra revision `0004`, hay que reapuntar
> `down_revision` (y renumerar) en vez de dejar dos revisiones con el mismo
> padre: Alembic no upgradea una cadena con dos heads.
"""
import sqlalchemy as sa
from alembic import op

revision = '0004_alquileres'
down_revision = '0003_proveedores_y_reparaciones'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('marca', sa.String(length=255), nullable=True),
    sa.Column('modelo', sa.String(length=255), nullable=True),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('codigo_interno', sa.String(length=100), nullable=True),
    sa.Column('mac', sa.String(length=50), nullable=True),
    sa.Column('imei', sa.String(length=50), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('accesorios', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('costo_compra', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('proveedor_compra_id', sa.Integer(), nullable=True),
    sa.Column('valor_reposicion', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('garantia_vence', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['proveedor_compra_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_interno'),
    sa.UniqueConstraint('serial')
    )
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activos_garantia_vence'), ['garantia_vence'], unique=False)
        batch_op.create_index(batch_op.f('ix_activos_proveedor_compra_id'), ['proveedor_compra_id'], unique=False)

    op.create_table('contratos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=50), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('propietario_cliente_id', sa.Integer(), nullable=True),
    sa.Column('sector_id', sa.Integer(), nullable=True),
    sa.Column('domicilio_instalacion', sa.String(length=500), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('renovacion_automatica', sa.Boolean(), nullable=False),
    sa.Column('periodicidad', sa.String(length=20), nullable=False),
    sa.Column('dia_vencimiento', sa.Integer(), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('metodo_actualizacion', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('responsable', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('archivo_pdf', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['propietario_cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_propietario_cliente_id'), ['propietario_cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_sector_id'), ['sector_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_tipo_contrato'), ['tipo_contrato'], unique=False)

    op.create_table('contratos_equipos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('activo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_instalacion', sa.Date(), nullable=False),
    sa.Column('fecha_retiro', sa.Date(), nullable=True),
    sa.Column('motivo_retiro', sa.String(length=50), nullable=True),
    sa.Column('reemplaza_a_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_instalador_id', sa.Integer(), nullable=True),
    sa.Column('incidencia_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activo_id'], ['activos.id'], ),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.ForeignKeyConstraint(['incidencia_id'], ['incidencias.id'], ),
    sa.ForeignKeyConstraint(['reemplaza_a_id'], ['contratos_equipos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_instalador_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos_equipos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_equipos_activo_id'), ['activo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_equipos_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_equipos_fecha_retiro'), ['fecha_retiro'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_equipos_incidencia_id'), ['incidencia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_equipos_reemplaza_a_id'), ['reemplaza_a_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_equipos_tecnico_instalador_id'), ['tecnico_instalador_id'], unique=False)

    op.create_table('contratos_precios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('vigencia_desde', sa.Date(), nullable=False),
    sa.Column('vigencia_hasta', sa.Date(), nullable=True),
    sa.Column('importe', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contratos_precios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contratos_precios_contrato_id'), ['contrato_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_precios_vigencia_desde'), ['vigencia_desde'], unique=False)
        batch_op.create_index(batch_op.f('ix_contratos_precios_vigencia_hasta'), ['vigencia_hasta'], unique=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contratos_precios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_precios_vigencia_hasta'))
        batch_op.drop_index(batch_op.f('ix_contratos_precios_vigencia_desde'))
        batch_op.drop_index(batch_op.f('ix_contratos_precios_contrato_id'))

    op.drop_table('contratos_precios')
    with op.batch_alter_table('contratos_equipos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_tecnico_instalador_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_reemplaza_a_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_incidencia_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_fecha_retiro'))
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_contrato_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_equipos_activo_id'))

    op.drop_table('contratos_equipos')
    with op.batch_alter_table('contratos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contratos_tipo_contrato'))
        batch_op.drop_index(batch_op.f('ix_contratos_sector_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_propietario_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_contratos_fecha_fin'))
        batch_op.drop_index(batch_op.f('ix_contratos_estado'))
        batch_op.drop_index(batch_op.f('ix_contratos_cliente_id'))

    op.drop_table('contratos')
    with op.batch_alter_table('activos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activos_proveedor_compra_id'))
        batch_op.drop_index(batch_op.f('ix_activos_garantia_vence'))

    op.drop_table('activos')
    # ### end Alembic commands ###
